spring.application.name=medical-appointment-bookings-api
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show.sql=true
platform=org.hibernate.dialect.PostgreSQLDialect
